/**
 * VoxPEP — Drug Database Seed
 *
 * 50+ Brazilian medications with real names, interactions, and safety data.
 * Can be imported and called from the main seed file.
 */

import { PrismaClient } from '@prisma/client';
import { v4 as uuidv4 } from 'uuid';

// ─── Pre-generated UUIDs for referential integrity (interactions) ───────────

const DRUG_IDS = {
  // Antibiotics
  amoxicilina: uuidv4(),
  azitromicina: uuidv4(),
  cefalexina: uuidv4(),
  ciprofloxacino: uuidv4(),
  levofloxacino: uuidv4(),
  metronidazol: uuidv4(),
  sulfaTrimetoprima: uuidv4(),
  amoxiClavulanato: uuidv4(),
  clindamicina: uuidv4(),
  gentamicina: uuidv4(),

  // Cardiovascular
  losartana: uuidv4(),
  enalapril: uuidv4(),
  anlodipino: uuidv4(),
  atenolol: uuidv4(),
  hidroclorotiazida: uuidv4(),
  furosemida: uuidv4(),
  sinvastatina: uuidv4(),
  aas: uuidv4(),

  // Diabetes
  metformina: uuidv4(),
  glibenclamida: uuidv4(),
  insulinaNph: uuidv4(),
  insulinaRegular: uuidv4(),
  gliclazida: uuidv4(),

  // Pain/Anti-inflammatory
  dipirona: uuidv4(),
  paracetamol: uuidv4(),
  ibuprofeno: uuidv4(),
  diclofenaco: uuidv4(),
  tramadol: uuidv4(),
  codeina: uuidv4(),

  // Psychotropics/Controlled
  diazepam: uuidv4(),
  clonazepam: uuidv4(),
  fluoxetina: uuidv4(),
  sertralina: uuidv4(),
  amitriptilina: uuidv4(),
  carbamazepina: uuidv4(),
  haloperidol: uuidv4(),
  risperidona: uuidv4(),

  // High-Alert
  heparina: uuidv4(),
  enoxaparina: uuidv4(),
  kcl: uuidv4(),
  midazolam: uuidv4(),
  fentanil: uuidv4(),
  norepinefrina: uuidv4(),
  morfina: uuidv4(),

  // Common
  omeprazol: uuidv4(),
  ranitidina: uuidv4(),
  ondansetrona: uuidv4(),
  dexametasona: uuidv4(),
  prednisona: uuidv4(),
  salbutamol: uuidv4(),

  // Additional (Warfarina needed for interactions)
  warfarina: uuidv4(),
};

// ─── Drug definitions ───────────────────────────────────────────────────────

interface DrugSeed {
  id: string;
  name: string;
  activeIngredient: string;
  therapeuticClass: string;
  pharmaceuticalForm: string;
  concentration: string;
  isControlled: boolean;
  controlType?: string;
  isAntimicrobial: boolean;
  isHighAlert: boolean;
  maxDosePerDay?: string;
  defaultRoute?: string;
  defaultFrequency?: string;
  pregnancyCategory?: string;
  beersListCriteria?: string;
  geriatricCaution: boolean;
  pediatricUse: boolean;
  renalAdjustment: boolean;
  hepaticAdjustment: boolean;
}

const drugs: DrugSeed[] = [
  // ─── Antibiotics (10) ───────────────────────────────────────────────────
  {
    id: DRUG_IDS.amoxicilina,
    name: 'Amoxicilina 500mg',
    activeIngredient: 'Amoxicilina',
    therapeuticClass: 'Antibiótico - Penicilina',
    pharmaceuticalForm: 'Cápsula',
    concentration: '500mg',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: false,
    maxDosePerDay: '3000',
    defaultRoute: 'VO',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'B',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.azitromicina,
    name: 'Azitromicina 500mg',
    activeIngredient: 'Azitromicina',
    therapeuticClass: 'Antibiótico - Macrolídeo',
    pharmaceuticalForm: 'Comprimido',
    concentration: '500mg',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: false,
    maxDosePerDay: '500',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'B',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.cefalexina,
    name: 'Cefalexina 500mg',
    activeIngredient: 'Cefalexina',
    therapeuticClass: 'Antibiótico - Cefalosporina 1a geração',
    pharmaceuticalForm: 'Cápsula',
    concentration: '500mg',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: false,
    maxDosePerDay: '4000',
    defaultRoute: 'VO',
    defaultFrequency: '6/6h',
    pregnancyCategory: 'B',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.ciprofloxacino,
    name: 'Ciprofloxacino 500mg',
    activeIngredient: 'Ciprofloxacino',
    therapeuticClass: 'Antibiótico - Fluoroquinolona',
    pharmaceuticalForm: 'Comprimido',
    concentration: '500mg',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: false,
    maxDosePerDay: '1500',
    defaultRoute: 'VO',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.levofloxacino,
    name: 'Levofloxacino 500mg',
    activeIngredient: 'Levofloxacino',
    therapeuticClass: 'Antibiótico - Fluoroquinolona',
    pharmaceuticalForm: 'Comprimido',
    concentration: '500mg',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: false,
    maxDosePerDay: '750',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.metronidazol,
    name: 'Metronidazol 400mg',
    activeIngredient: 'Metronidazol',
    therapeuticClass: 'Antibiótico - Nitroimidazólico',
    pharmaceuticalForm: 'Comprimido',
    concentration: '400mg',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: false,
    maxDosePerDay: '2000',
    defaultRoute: 'VO',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'B',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.sulfaTrimetoprima,
    name: 'Sulfametoxazol+Trimetoprima 400/80mg',
    activeIngredient: 'Sulfametoxazol + Trimetoprima',
    therapeuticClass: 'Antibiótico - Sulfonamida',
    pharmaceuticalForm: 'Comprimido',
    concentration: '400/80mg',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: false,
    maxDosePerDay: '1600',
    defaultRoute: 'VO',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.amoxiClavulanato,
    name: 'Amoxicilina+Clavulanato 875/125mg',
    activeIngredient: 'Amoxicilina + Ácido Clavulânico',
    therapeuticClass: 'Antibiótico - Penicilina + Inibidor de beta-lactamase',
    pharmaceuticalForm: 'Comprimido',
    concentration: '875/125mg',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: false,
    maxDosePerDay: '3000',
    defaultRoute: 'VO',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'B',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.clindamicina,
    name: 'Clindamicina 300mg',
    activeIngredient: 'Clindamicina',
    therapeuticClass: 'Antibiótico - Lincosamida',
    pharmaceuticalForm: 'Cápsula',
    concentration: '300mg',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: false,
    maxDosePerDay: '1800',
    defaultRoute: 'VO',
    defaultFrequency: '6/6h',
    pregnancyCategory: 'B',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.gentamicina,
    name: 'Gentamicina 80mg/2mL',
    activeIngredient: 'Gentamicina',
    therapeuticClass: 'Antibiótico - Aminoglicosídeo',
    pharmaceuticalForm: 'Solução injetável',
    concentration: '80mg/2mL',
    isControlled: false,
    isAntimicrobial: true,
    isHighAlert: true,
    maxDosePerDay: '360',
    defaultRoute: 'IV',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'D',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },

  // ─── Cardiovascular (8) ─────────────────────────────────────────────────
  {
    id: DRUG_IDS.losartana,
    name: 'Losartana 50mg',
    activeIngredient: 'Losartana',
    therapeuticClass: 'Anti-hipertensivo - BRA',
    pharmaceuticalForm: 'Comprimido',
    concentration: '50mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '100',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'D',
    geriatricCaution: false,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.enalapril,
    name: 'Enalapril 10mg',
    activeIngredient: 'Enalapril',
    therapeuticClass: 'Anti-hipertensivo - IECA',
    pharmaceuticalForm: 'Comprimido',
    concentration: '10mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '40',
    defaultRoute: 'VO',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'D',
    geriatricCaution: false,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.anlodipino,
    name: 'Anlodipino 5mg',
    activeIngredient: 'Anlodipino',
    therapeuticClass: 'Anti-hipertensivo - Bloqueador de canal de cálcio',
    pharmaceuticalForm: 'Comprimido',
    concentration: '5mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '10',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    geriatricCaution: false,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.atenolol,
    name: 'Atenolol 50mg',
    activeIngredient: 'Atenolol',
    therapeuticClass: 'Anti-hipertensivo - Betabloqueador',
    pharmaceuticalForm: 'Comprimido',
    concentration: '50mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '100',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'D',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.hidroclorotiazida,
    name: 'Hidroclorotiazida 25mg',
    activeIngredient: 'Hidroclorotiazida',
    therapeuticClass: 'Diurético tiazídico',
    pharmaceuticalForm: 'Comprimido',
    concentration: '25mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '50',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'B',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.furosemida,
    name: 'Furosemida 40mg',
    activeIngredient: 'Furosemida',
    therapeuticClass: 'Diurético de alça',
    pharmaceuticalForm: 'Comprimido',
    concentration: '40mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '600',
    defaultRoute: 'VO',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.sinvastatina,
    name: 'Sinvastatina 20mg',
    activeIngredient: 'Sinvastatina',
    therapeuticClass: 'Hipolipemiante - Estatina',
    pharmaceuticalForm: 'Comprimido',
    concentration: '20mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '80',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'X',
    geriatricCaution: false,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.aas,
    name: 'AAS 100mg',
    activeIngredient: 'Ácido Acetilsalicílico',
    therapeuticClass: 'Antiagregante plaquetário',
    pharmaceuticalForm: 'Comprimido',
    concentration: '100mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '300',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'D',
    geriatricCaution: false,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: false,
  },

  // ─── Diabetes (5) ───────────────────────────────────────────────────────
  {
    id: DRUG_IDS.metformina,
    name: 'Metformina 850mg',
    activeIngredient: 'Metformina',
    therapeuticClass: 'Antidiabético - Biguanida',
    pharmaceuticalForm: 'Comprimido',
    concentration: '850mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '2550',
    defaultRoute: 'VO',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'B',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.glibenclamida,
    name: 'Glibenclamida 5mg',
    activeIngredient: 'Glibenclamida',
    therapeuticClass: 'Antidiabético - Sulfonilureia',
    pharmaceuticalForm: 'Comprimido',
    concentration: '5mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '20',
    defaultRoute: 'VO',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Evitar em idosos. Alto risco de hipoglicemia prolongada. Preferir glicazida ou inibidores de DPP-4.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.insulinaNph,
    name: 'Insulina NPH 100UI/mL',
    activeIngredient: 'Insulina humana NPH',
    therapeuticClass: 'Antidiabético - Insulina intermediária',
    pharmaceuticalForm: 'Suspensão injetável',
    concentration: '100UI/mL',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: true,
    defaultRoute: 'SC',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'B',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.insulinaRegular,
    name: 'Insulina Regular 100UI/mL',
    activeIngredient: 'Insulina humana regular',
    therapeuticClass: 'Antidiabético - Insulina rápida',
    pharmaceuticalForm: 'Solução injetável',
    concentration: '100UI/mL',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: true,
    defaultRoute: 'SC',
    defaultFrequency: '6/6h',
    pregnancyCategory: 'B',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.gliclazida,
    name: 'Gliclazida 30mg',
    activeIngredient: 'Gliclazida',
    therapeuticClass: 'Antidiabético - Sulfonilureia',
    pharmaceuticalForm: 'Comprimido de liberação modificada',
    concentration: '30mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '120',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    geriatricCaution: false,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },

  // ─── Pain/Anti-inflammatory (6) ─────────────────────────────────────────
  {
    id: DRUG_IDS.dipirona,
    name: 'Dipirona 500mg',
    activeIngredient: 'Dipirona sódica',
    therapeuticClass: 'Analgésico / Antipirético',
    pharmaceuticalForm: 'Comprimido',
    concentration: '500mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '4000',
    defaultRoute: 'VO',
    defaultFrequency: '6/6h',
    pregnancyCategory: 'C',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.paracetamol,
    name: 'Paracetamol 750mg',
    activeIngredient: 'Paracetamol',
    therapeuticClass: 'Analgésico / Antipirético',
    pharmaceuticalForm: 'Comprimido',
    concentration: '750mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '4000',
    defaultRoute: 'VO',
    defaultFrequency: '6/6h',
    pregnancyCategory: 'B',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.ibuprofeno,
    name: 'Ibuprofeno 600mg',
    activeIngredient: 'Ibuprofeno',
    therapeuticClass: 'Anti-inflamatório não esteroidal (AINE)',
    pharmaceuticalForm: 'Comprimido',
    concentration: '600mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '2400',
    defaultRoute: 'VO',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Evitar uso crônico em idosos. Risco de sangramento GI, lesão renal e eventos cardiovasculares.',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.diclofenaco,
    name: 'Diclofenaco 50mg',
    activeIngredient: 'Diclofenaco sódico',
    therapeuticClass: 'Anti-inflamatório não esteroidal (AINE)',
    pharmaceuticalForm: 'Comprimido',
    concentration: '50mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '150',
    defaultRoute: 'VO',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Evitar uso crônico em idosos. Risco de sangramento GI e lesão renal.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.tramadol,
    name: 'Tramadol 50mg',
    activeIngredient: 'Tramadol',
    therapeuticClass: 'Analgésico opioide',
    pharmaceuticalForm: 'Cápsula',
    concentration: '50mg',
    isControlled: true,
    controlType: 'PORTARIA_344_C1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '400',
    defaultRoute: 'VO',
    defaultFrequency: '6/6h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Usar com cautela em idosos. Risco de sedação, quedas e convulsões. Preferir doses menores.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.codeina,
    name: 'Codeína 30mg',
    activeIngredient: 'Codeína',
    therapeuticClass: 'Analgésico opioide',
    pharmaceuticalForm: 'Comprimido',
    concentration: '30mg',
    isControlled: true,
    controlType: 'PORTARIA_344_A1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '240',
    defaultRoute: 'VO',
    defaultFrequency: '6/6h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Evitar em idosos. Risco de sedação, constipação, quedas. Preferir analgésicos não opioides.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },

  // ─── Psychotropics/Controlled (8) ───────────────────────────────────────
  {
    id: DRUG_IDS.diazepam,
    name: 'Diazepam 10mg',
    activeIngredient: 'Diazepam',
    therapeuticClass: 'Ansiolítico - Benzodiazepínico',
    pharmaceuticalForm: 'Comprimido',
    concentration: '10mg',
    isControlled: true,
    controlType: 'PORTARIA_344_B1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '40',
    defaultRoute: 'VO',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'D',
    beersListCriteria: 'Evitar em idosos. Benzodiazepínico de meia-vida longa. Risco de sedação excessiva, quedas, fraturas e delirium.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.clonazepam,
    name: 'Clonazepam 2mg',
    activeIngredient: 'Clonazepam',
    therapeuticClass: 'Ansiolítico / Anticonvulsivante - Benzodiazepínico',
    pharmaceuticalForm: 'Comprimido',
    concentration: '2mg',
    isControlled: true,
    controlType: 'PORTARIA_344_B1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '20',
    defaultRoute: 'VO',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'D',
    beersListCriteria: 'Evitar em idosos. Risco de sedação, quedas, fraturas e comprometimento cognitivo.',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.fluoxetina,
    name: 'Fluoxetina 20mg',
    activeIngredient: 'Fluoxetina',
    therapeuticClass: 'Antidepressivo - ISRS',
    pharmaceuticalForm: 'Cápsula',
    concentration: '20mg',
    isControlled: true,
    controlType: 'PORTARIA_344_C1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '80',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Usar com cautela em idosos. ISRS de meia-vida longa. Risco de hiponatremia (SIADH).',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.sertralina,
    name: 'Sertralina 50mg',
    activeIngredient: 'Sertralina',
    therapeuticClass: 'Antidepressivo - ISRS',
    pharmaceuticalForm: 'Comprimido',
    concentration: '50mg',
    isControlled: true,
    controlType: 'PORTARIA_344_C1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '200',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    geriatricCaution: false,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.amitriptilina,
    name: 'Amitriptilina 25mg',
    activeIngredient: 'Amitriptilina',
    therapeuticClass: 'Antidepressivo tricíclico',
    pharmaceuticalForm: 'Comprimido',
    concentration: '25mg',
    isControlled: true,
    controlType: 'PORTARIA_344_C1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '150',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Evitar em idosos. Efeitos anticolinérgicos fortes: sedação, hipotensão ortostática, constipação, retenção urinária, confusão.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.carbamazepina,
    name: 'Carbamazepina 200mg',
    activeIngredient: 'Carbamazepina',
    therapeuticClass: 'Anticonvulsivante / Estabilizador de humor',
    pharmaceuticalForm: 'Comprimido',
    concentration: '200mg',
    isControlled: true,
    controlType: 'PORTARIA_344_C1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '1200',
    defaultRoute: 'VO',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'D',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.haloperidol,
    name: 'Haloperidol 5mg',
    activeIngredient: 'Haloperidol',
    therapeuticClass: 'Antipsicótico típico',
    pharmaceuticalForm: 'Comprimido',
    concentration: '5mg',
    isControlled: true,
    controlType: 'PORTARIA_344_C1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '20',
    defaultRoute: 'VO',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Evitar em idosos com demência. Risco de AVC, mortalidade aumentada. Efeitos extrapiramidais.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.risperidona,
    name: 'Risperidona 2mg',
    activeIngredient: 'Risperidona',
    therapeuticClass: 'Antipsicótico atípico',
    pharmaceuticalForm: 'Comprimido',
    concentration: '2mg',
    isControlled: true,
    controlType: 'PORTARIA_344_C1',
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '8',
    defaultRoute: 'VO',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Evitar em idosos com demência. Risco de AVC e mortalidade aumentada.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },

  // ─── High-Alert (7) ────────────────────────────────────────────────────
  {
    id: DRUG_IDS.heparina,
    name: 'Heparina 5000UI/mL',
    activeIngredient: 'Heparina sódica',
    therapeuticClass: 'Anticoagulante',
    pharmaceuticalForm: 'Solução injetável',
    concentration: '5000UI/mL',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: true,
    defaultRoute: 'IV',
    defaultFrequency: '6/6h',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.enoxaparina,
    name: 'Enoxaparina 40mg',
    activeIngredient: 'Enoxaparina sódica',
    therapeuticClass: 'Anticoagulante - HBPM',
    pharmaceuticalForm: 'Solução injetável',
    concentration: '40mg/0,4mL',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: true,
    defaultRoute: 'SC',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'B',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.kcl,
    name: 'KCl 19,1%',
    activeIngredient: 'Cloreto de potássio',
    therapeuticClass: 'Eletrólito',
    pharmaceuticalForm: 'Solução injetável',
    concentration: '19,1%',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: true,
    defaultRoute: 'IV',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.midazolam,
    name: 'Midazolam 5mg/5mL IV',
    activeIngredient: 'Midazolam',
    therapeuticClass: 'Sedativo - Benzodiazepínico',
    pharmaceuticalForm: 'Solução injetável',
    concentration: '5mg/5mL',
    isControlled: true,
    controlType: 'PORTARIA_344_B1',
    isAntimicrobial: false,
    isHighAlert: true,
    maxDosePerDay: '20',
    defaultRoute: 'IV',
    defaultFrequency: 'Conforme necessidade',
    pregnancyCategory: 'D',
    beersListCriteria: 'Evitar em idosos. Risco de sedação profunda, depressão respiratória e delirium.',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.fentanil,
    name: 'Fentanil 50mcg/mL',
    activeIngredient: 'Fentanil',
    therapeuticClass: 'Analgésico opioide potente',
    pharmaceuticalForm: 'Solução injetável',
    concentration: '50mcg/mL',
    isControlled: true,
    controlType: 'PORTARIA_344_A1',
    isAntimicrobial: false,
    isHighAlert: true,
    defaultRoute: 'IV',
    defaultFrequency: 'Conforme necessidade',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.norepinefrina,
    name: 'Norepinefrina 2mg/mL',
    activeIngredient: 'Norepinefrina',
    therapeuticClass: 'Vasopressor',
    pharmaceuticalForm: 'Solução injetável',
    concentration: '2mg/mL',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: true,
    defaultRoute: 'IV',
    defaultFrequency: 'Infusão contínua',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.morfina,
    name: 'Morfina 10mg/mL',
    activeIngredient: 'Morfina',
    therapeuticClass: 'Analgésico opioide potente',
    pharmaceuticalForm: 'Solução injetável',
    concentration: '10mg/mL',
    isControlled: true,
    controlType: 'PORTARIA_344_A1',
    isAntimicrobial: false,
    isHighAlert: true,
    maxDosePerDay: '60',
    defaultRoute: 'IV',
    defaultFrequency: '4/4h',
    pregnancyCategory: 'C',
    beersListCriteria: 'Evitar em idosos. Risco de sedação, depressão respiratória, constipação e quedas.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: true,
    hepaticAdjustment: true,
  },

  // ─── Common (6) ─────────────────────────────────────────────────────────
  {
    id: DRUG_IDS.omeprazol,
    name: 'Omeprazol 20mg',
    activeIngredient: 'Omeprazol',
    therapeuticClass: 'Inibidor de bomba de prótons',
    pharmaceuticalForm: 'Cápsula',
    concentration: '20mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '40',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.ranitidina,
    name: 'Ranitidina 150mg',
    activeIngredient: 'Ranitidina',
    therapeuticClass: 'Antagonista H2',
    pharmaceuticalForm: 'Comprimido',
    concentration: '150mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '300',
    defaultRoute: 'VO',
    defaultFrequency: '12/12h',
    pregnancyCategory: 'B',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: true,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.ondansetrona,
    name: 'Ondansetrona 8mg',
    activeIngredient: 'Ondansetrona',
    therapeuticClass: 'Antiemético - Antagonista 5-HT3',
    pharmaceuticalForm: 'Comprimido',
    concentration: '8mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '32',
    defaultRoute: 'VO',
    defaultFrequency: '8/8h',
    pregnancyCategory: 'B',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
  {
    id: DRUG_IDS.dexametasona,
    name: 'Dexametasona 4mg',
    activeIngredient: 'Dexametasona',
    therapeuticClass: 'Corticosteroide',
    pharmaceuticalForm: 'Comprimido',
    concentration: '4mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '20',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.prednisona,
    name: 'Prednisona 20mg',
    activeIngredient: 'Prednisona',
    therapeuticClass: 'Corticosteroide',
    pharmaceuticalForm: 'Comprimido',
    concentration: '20mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    maxDosePerDay: '80',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'C',
    geriatricCaution: true,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: false,
  },
  {
    id: DRUG_IDS.salbutamol,
    name: 'Salbutamol spray 100mcg',
    activeIngredient: 'Salbutamol',
    therapeuticClass: 'Broncodilatador - Beta-2 agonista',
    pharmaceuticalForm: 'Aerossol dosimetrado',
    concentration: '100mcg/dose',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: false,
    defaultRoute: 'Inalatória',
    defaultFrequency: '6/6h',
    pregnancyCategory: 'C',
    geriatricCaution: false,
    pediatricUse: true,
    renalAdjustment: false,
    hepaticAdjustment: false,
  },

  // ─── Additional (Warfarina, needed for interactions) ────────────────────
  {
    id: DRUG_IDS.warfarina,
    name: 'Warfarina 5mg',
    activeIngredient: 'Warfarina sódica',
    therapeuticClass: 'Anticoagulante oral - Antagonista de vitamina K',
    pharmaceuticalForm: 'Comprimido',
    concentration: '5mg',
    isControlled: false,
    isAntimicrobial: false,
    isHighAlert: true,
    maxDosePerDay: '10',
    defaultRoute: 'VO',
    defaultFrequency: '24/24h',
    pregnancyCategory: 'X',
    beersListCriteria: 'Usar com cautela em idosos. Alto risco de sangramento. Monitorar INR frequentemente.',
    geriatricCaution: true,
    pediatricUse: false,
    renalAdjustment: false,
    hepaticAdjustment: true,
  },
];

// ─── Drug Interactions (15+) ────────────────────────────────────────────────

interface InteractionSeed {
  drug1Id: string;
  drug2Id: string;
  severity: string;
  mechanism: string;
  effect: string;
  management: string;
  evidence: string;
  source: string;
}

const interactions: InteractionSeed[] = [
  {
    drug1Id: DRUG_IDS.warfarina,
    drug2Id: DRUG_IDS.aas,
    severity: 'SEVERE',
    mechanism: 'Inibição da agregação plaquetária + anticoagulação',
    effect: 'Risco significativamente aumentado de sangramento, incluindo hemorragia gastrointestinal e intracraniana.',
    management: 'Evitar associação sempre que possível. Se necessário, monitorar INR rigorosamente e sinais de sangramento.',
    evidence: 'HIGH',
    source: 'MICROMEDEX',
  },
  {
    drug1Id: DRUG_IDS.ciprofloxacino,
    drug2Id: DRUG_IDS.metformina,
    severity: 'MODERATE',
    mechanism: 'Ciprofloxacino pode alterar secreção de insulina e metabolismo da metformina',
    effect: 'Risco de hipoglicemia ou hiperglicemia. Alterações na glicemia podem ser imprevisíveis.',
    management: 'Monitorar glicemia capilar mais frequentemente durante o uso concomitante. Ajustar dose se necessário.',
    evidence: 'MODERATE',
    source: 'ANVISA',
  },
  {
    drug1Id: DRUG_IDS.fluoxetina,
    drug2Id: DRUG_IDS.tramadol,
    severity: 'SEVERE',
    mechanism: 'Inibição da recaptação de serotonina por ambos os fármacos',
    effect: 'Risco de síndrome serotoninérgica: agitação, hipertermia, taquicardia, mioclonia, hiperreflexia. Potencialmente fatal.',
    management: 'EVITAR associação. Se indispensável, usar doses mínimas e monitorar sinais de síndrome serotoninérgica.',
    evidence: 'HIGH',
    source: 'MICROMEDEX',
  },
  {
    drug1Id: DRUG_IDS.diazepam,
    drug2Id: DRUG_IDS.morfina,
    severity: 'SEVERE',
    mechanism: 'Depressão aditiva do SNC por ambos os fármacos',
    effect: 'Depressão respiratória grave, sedação profunda, coma e óbito. Risco especialmente elevado em idosos.',
    management: 'EVITAR associação. Se necessário, reduzir doses de ambos em 50% e monitorar SpO2 continuamente.',
    evidence: 'HIGH',
    source: 'MICROMEDEX',
  },
  {
    drug1Id: DRUG_IDS.enalapril,
    drug2Id: DRUG_IDS.kcl,
    severity: 'MODERATE',
    mechanism: 'IECAs reduzem excreção renal de potássio + suplementação exógena',
    effect: 'Hipercalemia (K+ > 5,5 mEq/L). Risco de arritmias cardíacas graves.',
    management: 'Monitorar potássio sérico a cada 48-72h. Ajustar suplementação conforme níveis.',
    evidence: 'HIGH',
    source: 'ANVISA',
  },
  {
    drug1Id: DRUG_IDS.losartana,
    drug2Id: DRUG_IDS.kcl,
    severity: 'MODERATE',
    mechanism: 'BRAs reduzem excreção renal de potássio + suplementação exógena',
    effect: 'Hipercalemia (K+ > 5,5 mEq/L). Risco de arritmias cardíacas graves.',
    management: 'Monitorar potássio sérico a cada 48-72h. Ajustar suplementação conforme níveis.',
    evidence: 'HIGH',
    source: 'ANVISA',
  },
  {
    drug1Id: DRUG_IDS.metformina,
    drug2Id: DRUG_IDS.furosemida,
    severity: 'MODERATE',
    mechanism: 'Furosemida pode causar desidratação e disfunção renal, acumulando metformina',
    effect: 'Risco aumentado de acidose lática, especialmente em pacientes com função renal comprometida.',
    management: 'Monitorar função renal (creatinina, TFG). Garantir hidratação adequada. Suspender metformina se TFG < 30.',
    evidence: 'MODERATE',
    source: 'UPTODATE',
  },
  {
    drug1Id: DRUG_IDS.sinvastatina,
    drug2Id: DRUG_IDS.azitromicina,
    severity: 'MODERATE',
    mechanism: 'Azitromicina pode inibir metabolismo da sinvastatina via CYP3A4',
    effect: 'Risco aumentado de rabdomiólise: dor muscular, fraqueza, urina escura, elevação de CPK.',
    management: 'Monitorar sintomas musculares. Considerar suspensão temporária da estatina durante tratamento com azitromicina.',
    evidence: 'MODERATE',
    source: 'MICROMEDEX',
  },
  {
    drug1Id: DRUG_IDS.aas,
    drug2Id: DRUG_IDS.ibuprofeno,
    severity: 'MODERATE',
    mechanism: 'Ibuprofeno compete pelo sítio de ligação da COX-1, bloqueando efeito antiagregante do AAS',
    effect: 'Redução da cardioproteção do AAS. Risco aumentado de eventos cardiovasculares.',
    management: 'Administrar AAS 30 min antes do ibuprofeno, ou usar outro analgésico (paracetamol).',
    evidence: 'HIGH',
    source: 'ANVISA',
  },
  {
    drug1Id: DRUG_IDS.clonazepam,
    drug2Id: DRUG_IDS.fentanil,
    severity: 'SEVERE',
    mechanism: 'Depressão aditiva do SNC: benzodiazepínico + opioide potente',
    effect: 'Depressão respiratória grave, sedação profunda, coma e óbito.',
    management: 'EVITAR associação. Se necessário, reduzir doses e monitorar com oximetria contínua e capnografia.',
    evidence: 'HIGH',
    source: 'MICROMEDEX',
  },
  {
    drug1Id: DRUG_IDS.haloperidol,
    drug2Id: DRUG_IDS.amitriptilina,
    severity: 'MODERATE',
    mechanism: 'Ambos prolongam intervalo QT no ECG',
    effect: 'Risco de prolongamento QT, torsades de pointes e arritmias potencialmente fatais.',
    management: 'Realizar ECG antes e após início. Monitorar intervalo QTc. Evitar em pacientes com QTc > 470ms.',
    evidence: 'MODERATE',
    source: 'UPTODATE',
  },
  {
    drug1Id: DRUG_IDS.carbamazepina,
    drug2Id: DRUG_IDS.fluoxetina,
    severity: 'MODERATE',
    mechanism: 'Fluoxetina inibe CYP3A4, reduzindo metabolismo da carbamazepina',
    effect: 'Toxicidade por carbamazepina: diplopia, ataxia, nistagmo, tontura, náuseas.',
    management: 'Monitorar nível sérico de carbamazepina. Reduzir dose se necessário. Observar sinais de toxicidade.',
    evidence: 'HIGH',
    source: 'MICROMEDEX',
  },
  {
    drug1Id: DRUG_IDS.heparina,
    drug2Id: DRUG_IDS.aas,
    severity: 'SEVERE',
    mechanism: 'Anticoagulação + inibição da agregação plaquetária',
    effect: 'Risco significativamente aumentado de hemorragia.',
    management: 'Avaliar risco-benefício cuidadosamente. Monitorar TTPa, plaquetas e sinais de sangramento.',
    evidence: 'HIGH',
    source: 'ANVISA',
  },
  {
    drug1Id: DRUG_IDS.enalapril,
    drug2Id: DRUG_IDS.losartana,
    severity: 'MODERATE',
    mechanism: 'Duplo bloqueio do sistema renina-angiotensina-aldosterona',
    effect: 'Risco aumentado de hipotensão, hipercalemia e insuficiência renal aguda.',
    management: 'EVITAR associação. Duplo bloqueio do SRAA não é recomendado na maioria dos casos.',
    evidence: 'HIGH',
    source: 'UPTODATE',
  },
  {
    drug1Id: DRUG_IDS.midazolam,
    drug2Id: DRUG_IDS.fentanil,
    severity: 'SEVERE',
    mechanism: 'Sedação sinérgica: benzodiazepínico + opioide',
    effect: 'Sedação profunda, depressão respiratória grave, apneia. Risco de parada respiratória.',
    management: 'Usar apenas em ambiente monitorizado (UTI/centro cirúrgico). Reduzir doses. Ter flumazenil e naloxona disponíveis.',
    evidence: 'HIGH',
    source: 'MICROMEDEX',
  },
  {
    drug1Id: DRUG_IDS.warfarina,
    drug2Id: DRUG_IDS.metronidazol,
    severity: 'SEVERE',
    mechanism: 'Metronidazol inibe CYP2C9, reduzindo metabolismo da warfarina',
    effect: 'Aumento significativo do INR e risco de hemorragia.',
    management: 'Monitorar INR a cada 2-3 dias. Reduzir dose de warfarina em 25-50% durante uso de metronidazol.',
    evidence: 'HIGH',
    source: 'MICROMEDEX',
  },
];

// ─── Seed function ──────────────────────────────────────────────────────────

export async function seedDrugs(prisma: PrismaClient): Promise<void> {
  console.log('\n📦 Seeding Drug Database...');

  // Clean existing data
  console.log('  → Cleaning existing drug data...');
  await prisma.drugInteraction.deleteMany({});
  await prisma.drug.deleteMany({});

  // Seed drugs
  console.log(`  → Creating ${drugs.length} drugs...`);
  for (const drug of drugs) {
    await prisma.drug.create({
      data: {
        id: drug.id,
        tenantId: null, // Global/system drugs
        name: drug.name,
        activeIngredient: drug.activeIngredient,
        therapeuticClass: drug.therapeuticClass,
        pharmaceuticalForm: drug.pharmaceuticalForm,
        concentration: drug.concentration,
        isControlled: drug.isControlled,
        controlType: drug.controlType ?? null,
        isAntimicrobial: drug.isAntimicrobial,
        isHighAlert: drug.isHighAlert,
        maxDosePerDay: drug.maxDosePerDay ?? null,
        defaultRoute: drug.defaultRoute ?? null,
        defaultFrequency: drug.defaultFrequency ?? null,
        pregnancyCategory: drug.pregnancyCategory ?? null,
        beersListCriteria: drug.beersListCriteria ?? null,
        geriatricCaution: drug.geriatricCaution,
        pediatricUse: drug.pediatricUse,
        renalAdjustment: drug.renalAdjustment,
        hepaticAdjustment: drug.hepaticAdjustment,
      },
    });
  }

  // Seed interactions
  console.log(`  → Creating ${interactions.length} drug interactions...`);
  for (const interaction of interactions) {
    await prisma.drugInteraction.create({
      data: {
        id: uuidv4(),
        drug1Id: interaction.drug1Id,
        drug2Id: interaction.drug2Id,
        severity: interaction.severity,
        mechanism: interaction.mechanism,
        effect: interaction.effect,
        management: interaction.management,
        evidence: interaction.evidence,
        source: interaction.source,
      },
    });
  }

  console.log('  ✅ Drug Database seeded:');
  console.log(`     - ${drugs.length} medications`);
  console.log(`     - ${interactions.length} drug interactions`);
  console.log(`     - ${drugs.filter((d) => d.isHighAlert).length} high-alert medications`);
  console.log(`     - ${drugs.filter((d) => d.isControlled).length} controlled substances`);
  console.log(`     - ${drugs.filter((d) => d.isAntimicrobial).length} antimicrobials`);
}
