export const ROLES = {
  SYSTEM_ADMIN: 'SYSTEM_ADMIN',
  TENANT_ADMIN: 'TENANT_ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  RECEPTIONIST: 'RECEPTIONIST',
  PHARMACIST: 'PHARMACIST',
  LAB_TECHNICIAN: 'LAB_TECHNICIAN',
  BILLING: 'BILLING',
  VIEWER: 'VIEWER',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_HIERARCHY: Record<string, string[]> = {
  [ROLES.SYSTEM_ADMIN]: Object.values(ROLES),
  [ROLES.TENANT_ADMIN]: [
    ROLES.TENANT_ADMIN,
    ROLES.DOCTOR,
    ROLES.NURSE,
    ROLES.RECEPTIONIST,
    ROLES.PHARMACIST,
    ROLES.LAB_TECHNICIAN,
    ROLES.BILLING,
    ROLES.VIEWER,
  ],
  [ROLES.DOCTOR]: [ROLES.DOCTOR, ROLES.VIEWER],
  [ROLES.NURSE]: [ROLES.NURSE, ROLES.VIEWER],
  [ROLES.RECEPTIONIST]: [ROLES.RECEPTIONIST, ROLES.VIEWER],
  [ROLES.PHARMACIST]: [ROLES.PHARMACIST, ROLES.VIEWER],
  [ROLES.LAB_TECHNICIAN]: [ROLES.LAB_TECHNICIAN, ROLES.VIEWER],
  [ROLES.BILLING]: [ROLES.BILLING, ROLES.VIEWER],
  [ROLES.VIEWER]: [ROLES.VIEWER],
};
