import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsString,
  IsUUID,
  IsOptional,
  IsEnum,
  IsBoolean,
  IsArray,
} from 'class-validator';
import { NoteType, UserRole } from '@prisma/client';

export class CreateClinicalNoteDto {
  @ApiProperty({ description: 'Encounter ID' })
  @IsUUID()
  @IsNotEmpty()
  encounterId: string;

  @ApiProperty({ description: 'Note type', enum: NoteType })
  @IsEnum(NoteType)
  type: NoteType;

  @ApiPropertyOptional({ description: 'Author role', enum: UserRole })
  @IsOptional()
  @IsEnum(UserRole)
  authorRole?: UserRole;

  @ApiPropertyOptional({ description: 'Subjective (SOAP)' })
  @IsOptional()
  @IsString()
  subjective?: string;

  @ApiPropertyOptional({ description: 'Objective (SOAP)' })
  @IsOptional()
  @IsString()
  objective?: string;

  @ApiPropertyOptional({ description: 'Assessment (SOAP)' })
  @IsOptional()
  @IsString()
  assessment?: string;

  @ApiPropertyOptional({ description: 'Plan (SOAP)' })
  @IsOptional()
  @IsString()
  plan?: string;

  @ApiPropertyOptional({ description: 'Free text content' })
  @IsOptional()
  @IsString()
  freeText?: string;

  @ApiPropertyOptional({ description: 'Diagnosis ICD codes', type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  diagnosisCodes?: string[];

  @ApiPropertyOptional({ description: 'Procedure codes', type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  procedureCodes?: string[];

  @ApiPropertyOptional({ description: 'Voice transcription ID' })
  @IsOptional()
  @IsUUID()
  voiceTranscriptionId?: string;

  @ApiPropertyOptional({ description: 'Was generated by AI' })
  @IsOptional()
  @IsBoolean()
  wasGeneratedByAI?: boolean;
}
