export interface MedicationReference {
  name: string;
  activeIngredient: string;
  class: string;
  commonDoses: string[];
  commonRoutes: string[];
  commonFrequencies: string[];
  maxDailyDose?: string;
  isControlled: boolean;
  controlledSchedule?: string;
  isHighAlert: boolean;
  isAntibiotic: boolean;
  pregnancyCategory: string;
  renalAdjustment: boolean;
  hepaticAdjustment: boolean;
  commonInteractions: string[];
  contraindications: string[];
  beersListElderly: boolean;
}

/**
 * Medicamentos mais prescritos em hospitais brasileiros.
 * Referências: Formulário Terapêutico Nacional, RENAME, bulas ANVISA.
 */
export const COMMON_MEDICATIONS: readonly MedicationReference[] = [
  // ─── Analgésicos / Antitérmicos ─────────────────────────────────
  {
    name: 'Dipirona',
    activeIngredient: 'Metamizol sódico',
    class: 'Analgésico / Antitérmico',
    commonDoses: ['500 mg', '1 g', '2 mL (500 mg/mL)'],
    commonRoutes: ['VO', 'IV', 'IM'],
    commonFrequencies: ['6/6h', '8/8h'],
    maxDailyDose: '4 g',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'D',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Metotrexato', 'Ciclosporina', 'Anticoagulantes orais'],
    contraindications: ['Hipersensibilidade a pirazolonas', 'Porfiria', 'Deficiência de G6PD', 'Gestação (1º e 3º trimestre)'],
    beersListElderly: false,
  },
  {
    name: 'Paracetamol',
    activeIngredient: 'Paracetamol (Acetaminofeno)',
    class: 'Analgésico / Antitérmico',
    commonDoses: ['500 mg', '750 mg', '1 g'],
    commonRoutes: ['VO'],
    commonFrequencies: ['6/6h', '8/8h'],
    maxDailyDose: '4 g (adultos); 2 g (hepatopatas)',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Warfarina', 'Álcool'],
    contraindications: ['Hipersensibilidade', 'Doença hepática grave'],
    beersListElderly: false,
  },
  {
    name: 'Cetoprofeno',
    activeIngredient: 'Cetoprofeno',
    class: 'Anti-inflamatório não esteroidal (AINE)',
    commonDoses: ['50 mg', '100 mg', '100 mg IV'],
    commonRoutes: ['VO', 'IV', 'IM'],
    commonFrequencies: ['8/8h', '12/12h'],
    maxDailyDose: '300 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Anticoagulantes', 'Metotrexato', 'Lítio', 'AAS', 'Corticosteroides'],
    contraindications: ['Úlcera péptica ativa', 'Insuficiência renal grave', 'Gestação 3º trimestre', 'Asma por AINE'],
    beersListElderly: true,
  },
  {
    name: 'Tramadol',
    activeIngredient: 'Cloridrato de tramadol',
    class: 'Opioide fraco',
    commonDoses: ['50 mg', '100 mg', '100 mg IV (diluído)'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['6/6h', '8/8h'],
    maxDailyDose: '400 mg',
    isControlled: true,
    controlledSchedule: 'A2',
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['ISRS', 'IRSN', 'IMAO', 'Carbamazepina', 'Ondansetrona'],
    contraindications: ['Uso de IMAO', 'Epilepsia não controlada', 'Intoxicação aguda por álcool/opioides/hipnóticos'],
    beersListElderly: true,
  },
  {
    name: 'Morfina',
    activeIngredient: 'Sulfato de morfina',
    class: 'Opioide forte',
    commonDoses: ['2 mg IV', '5 mg IV', '10 mg SC', '10 mg VO', '30 mg VO'],
    commonRoutes: ['IV', 'SC', 'VO'],
    commonFrequencies: ['4/4h', '6/6h'],
    maxDailyDose: 'Sem teto (titulação conforme dor)',
    isControlled: true,
    controlledSchedule: 'A1',
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Benzodiazepínicos', 'Outros opioides', 'IMAO', 'Álcool'],
    contraindications: ['Depressão respiratória', 'Íleo paralítico', 'Uso de IMAO nos últimos 14 dias'],
    beersListElderly: true,
  },

  // ─── Antibióticos ───────────────────────────────────────────────
  {
    name: 'Ceftriaxona',
    activeIngredient: 'Ceftriaxona dissódica',
    class: 'Cefalosporina 3ª geração',
    commonDoses: ['1 g', '2 g'],
    commonRoutes: ['IV', 'IM'],
    commonFrequencies: ['12/12h', '24/24h'],
    maxDailyDose: '4 g',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: true,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['Soluções contendo cálcio (não misturar)', 'Warfarina'],
    contraindications: ['Alergia a cefalosporinas', 'Neonatos hiperbilirrubinêmicos (precipitação com cálcio)'],
    beersListElderly: false,
  },
  {
    name: 'Amoxicilina + Clavulanato',
    activeIngredient: 'Amoxicilina + Ácido clavulânico',
    class: 'Penicilina + Inibidor de beta-lactamase',
    commonDoses: ['500/125 mg', '875/125 mg', '1 g/200 mg IV'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['8/8h', '12/12h'],
    maxDailyDose: '3 g de amoxicilina',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: true,
    pregnancyCategory: 'B',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Metotrexato', 'Warfarina', 'Alopurinol'],
    contraindications: ['Alergia a penicilinas', 'Icterícia/disfunção hepática prévia pelo uso'],
    beersListElderly: false,
  },
  {
    name: 'Ciprofloxacino',
    activeIngredient: 'Cloridrato de ciprofloxacino',
    class: 'Fluoroquinolona',
    commonDoses: ['250 mg', '500 mg', '400 mg IV'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['12/12h'],
    maxDailyDose: '1,5 g VO / 1,2 g IV',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: true,
    pregnancyCategory: 'C',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['Teofilina', 'Warfarina', 'Ciclosporina', 'Antiácidos (reduzem absorção)'],
    contraindications: ['Hipersensibilidade a quinolonas', 'Uso concomitante de tizanidina', 'Miastenia gravis (risco relativo)'],
    beersListElderly: true,
  },
  {
    name: 'Piperacilina + Tazobactam',
    activeIngredient: 'Piperacilina sódica + Tazobactam sódico',
    class: 'Penicilina de amplo espectro + Inibidor de beta-lactamase',
    commonDoses: ['4,5 g (4 g/0,5 g)'],
    commonRoutes: ['IV'],
    commonFrequencies: ['6/6h', '8/8h'],
    maxDailyDose: '18 g de piperacilina',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: true,
    pregnancyCategory: 'B',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['Metotrexato', 'Aminoglicosídeos (inativar se na mesma via)', 'Anticoagulantes'],
    contraindications: ['Alergia a penicilinas', 'Alergia a inibidores de beta-lactamase'],
    beersListElderly: false,
  },
  {
    name: 'Vancomicina',
    activeIngredient: 'Cloridrato de vancomicina',
    class: 'Glicopeptídeo',
    commonDoses: ['500 mg', '1 g'],
    commonRoutes: ['IV'],
    commonFrequencies: ['6/6h', '8/8h', '12/12h'],
    maxDailyDose: '4 g (ajuste por nível sérico)',
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: true,
    pregnancyCategory: 'C',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['Aminoglicosídeos (nefrotoxicidade aditiva)', 'Anestésicos'],
    contraindications: ['Hipersensibilidade à vancomicina'],
    beersListElderly: false,
  },
  {
    name: 'Metronidazol',
    activeIngredient: 'Metronidazol',
    class: 'Nitroimidazol',
    commonDoses: ['250 mg', '400 mg', '500 mg IV'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['8/8h'],
    maxDailyDose: '4 g',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: true,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Álcool (efeito dissulfiram)', 'Warfarina', 'Lítio', 'Fenitoína'],
    contraindications: ['Hipersensibilidade', 'Primeiro trimestre de gestação', 'Uso de álcool'],
    beersListElderly: false,
  },
  {
    name: 'Azitromicina',
    activeIngredient: 'Azitromicina di-hidratada',
    class: 'Macrolídeo',
    commonDoses: ['500 mg', '500 mg IV'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['24/24h'],
    maxDailyDose: '500 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: true,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Warfarina', 'Digoxina', 'Ergotamina', 'Ciclosporina'],
    contraindications: ['Hipersensibilidade a macrolídeos', 'Hepatopatia grave'],
    beersListElderly: false,
  },
  {
    name: 'Meropenem',
    activeIngredient: 'Meropenem tri-hidratado',
    class: 'Carbapenêmico',
    commonDoses: ['500 mg', '1 g', '2 g'],
    commonRoutes: ['IV'],
    commonFrequencies: ['8/8h'],
    maxDailyDose: '6 g',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: true,
    pregnancyCategory: 'B',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['Ácido valproico (reduz níveis)', 'Probenecida'],
    contraindications: ['Hipersensibilidade a carbapenêmicos'],
    beersListElderly: false,
  },

  // ─── Anti-hipertensivos ─────────────────────────────────────────
  {
    name: 'Enalapril',
    activeIngredient: 'Maleato de enalapril',
    class: 'Inibidor da ECA (IECA)',
    commonDoses: ['5 mg', '10 mg', '20 mg'],
    commonRoutes: ['VO'],
    commonFrequencies: ['12/12h', '24/24h'],
    maxDailyDose: '40 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'D',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['Espironolactona (hipercalemia)', 'AINEs', 'Lítio', 'Suplementos de potássio'],
    contraindications: ['Gestação', 'Angioedema prévio por IECA', 'Estenose bilateral de artéria renal'],
    beersListElderly: false,
  },
  {
    name: 'Losartana',
    activeIngredient: 'Losartana potássica',
    class: 'Bloqueador do receptor de angiotensina II (BRA)',
    commonDoses: ['25 mg', '50 mg', '100 mg'],
    commonRoutes: ['VO'],
    commonFrequencies: ['12/12h', '24/24h'],
    maxDailyDose: '100 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'D',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Espironolactona', 'AINEs', 'Lítio', 'Suplementos de potássio'],
    contraindications: ['Gestação', 'Hipercalemia grave', 'Estenose bilateral de artéria renal'],
    beersListElderly: false,
  },
  {
    name: 'Anlodipino',
    activeIngredient: 'Besilato de anlodipino',
    class: 'Bloqueador de canal de cálcio (BCC)',
    commonDoses: ['2,5 mg', '5 mg', '10 mg'],
    commonRoutes: ['VO'],
    commonFrequencies: ['24/24h'],
    maxDailyDose: '10 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Sinvastatina (doses altas)', 'Ciclosporina', 'Tacrolimo'],
    contraindications: ['Hipersensibilidade', 'Choque cardiogênico', 'Estenose aórtica grave'],
    beersListElderly: false,
  },
  {
    name: 'Furosemida',
    activeIngredient: 'Furosemida',
    class: 'Diurético de alça',
    commonDoses: ['20 mg', '40 mg', '20 mg IV'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['12/12h', '24/24h', '8/8h'],
    maxDailyDose: '600 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['Aminoglicosídeos (ototoxicidade)', 'Digoxina (hipocalemia)', 'AINEs', 'Lítio'],
    contraindications: ['Anúria', 'Depleção grave de eletrólitos', 'Hipersensibilidade a sulfonamidas (reatividade cruzada possível)'],
    beersListElderly: true,
  },
  {
    name: 'Espironolactona',
    activeIngredient: 'Espironolactona',
    class: 'Diurético poupador de potássio',
    commonDoses: ['25 mg', '50 mg', '100 mg'],
    commonRoutes: ['VO'],
    commonFrequencies: ['24/24h', '12/12h'],
    maxDailyDose: '400 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'D',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['IECA/BRA (hipercalemia)', 'Suplementos de potássio', 'AINEs', 'Digoxina'],
    contraindications: ['Insuficiência renal aguda', 'Hipercalemia', 'Doença de Addison', 'Gestação'],
    beersListElderly: false,
  },

  // ─── Antidiabéticos ─────────────────────────────────────────────
  {
    name: 'Insulina Regular',
    activeIngredient: 'Insulina humana regular',
    class: 'Insulina de ação rápida',
    commonDoses: ['Conforme protocolo de correção', '0,1 UI/kg/h (BIC)'],
    commonRoutes: ['SC', 'IV'],
    commonFrequencies: ['Conforme glicemia', '6/6h', 'BIC'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Beta-bloqueadores (mascaram hipoglicemia)', 'Corticosteroides', 'Diuréticos tiazídicos'],
    contraindications: ['Hipoglicemia'],
    beersListElderly: false,
  },
  {
    name: 'Insulina NPH',
    activeIngredient: 'Insulina humana NPH',
    class: 'Insulina de ação intermediária',
    commonDoses: ['10 UI', '20 UI', '30 UI', 'Conforme esquema'],
    commonRoutes: ['SC'],
    commonFrequencies: ['12/12h', '24/24h'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Beta-bloqueadores', 'Corticosteroides', 'Diuréticos tiazídicos'],
    contraindications: ['Hipoglicemia'],
    beersListElderly: false,
  },
  {
    name: 'Metformina',
    activeIngredient: 'Cloridrato de metformina',
    class: 'Biguanida',
    commonDoses: ['500 mg', '850 mg', '1 g'],
    commonRoutes: ['VO'],
    commonFrequencies: ['12/12h', '8/8h'],
    maxDailyDose: '2.550 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Contraste iodado (suspender 48h antes)', 'Álcool'],
    contraindications: ['TFG < 30 mL/min', 'Insuficiência hepática grave', 'Acidose láctica', 'Uso de contraste iodado recente'],
    beersListElderly: false,
  },

  // ─── Anticoagulantes ────────────────────────────────────────────
  {
    name: 'Enoxaparina',
    activeIngredient: 'Enoxaparina sódica',
    class: 'Heparina de baixo peso molecular',
    commonDoses: ['20 mg', '40 mg', '60 mg', '80 mg', '1 mg/kg'],
    commonRoutes: ['SC'],
    commonFrequencies: ['12/12h', '24/24h'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['AINEs', 'AAS', 'Outros anticoagulantes', 'Antiplaquetários'],
    contraindications: ['Sangramento ativo', 'Trombocitopenia por heparina (HIT)', 'Hipersensibilidade à heparina'],
    beersListElderly: false,
  },
  {
    name: 'Heparina Não Fracionada',
    activeIngredient: 'Heparina sódica',
    class: 'Anticoagulante',
    commonDoses: ['5.000 UI SC', 'BIC conforme protocolo (ex: 18 UI/kg/h)'],
    commonRoutes: ['SC', 'IV'],
    commonFrequencies: ['8/8h (SC profilático)', 'BIC (terapêutico)'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['AINEs', 'AAS', 'Outros anticoagulantes', 'Estreptoquinase'],
    contraindications: ['Sangramento ativo', 'HIT', 'Hipersensibilidade', 'Hemofilia'],
    beersListElderly: false,
  },
  {
    name: 'Warfarina',
    activeIngredient: 'Warfarina sódica',
    class: 'Antagonista de vitamina K',
    commonDoses: ['1 mg', '2,5 mg', '5 mg', '7,5 mg'],
    commonRoutes: ['VO'],
    commonFrequencies: ['24/24h'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'X',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['AINEs', 'AAS', 'Amiodarona', 'Metronidazol', 'Fluconazol', 'Rifampicina', 'Vitamina K'],
    contraindications: ['Gestação', 'Sangramento ativo', 'Cirurgia recente do SNC/olho', 'Diátese hemorrágica'],
    beersListElderly: true,
  },

  // ─── Inibidores de Bomba de Prótons ─────────────────────────────
  {
    name: 'Omeprazol',
    activeIngredient: 'Omeprazol',
    class: 'Inibidor de bomba de prótons (IBP)',
    commonDoses: ['20 mg', '40 mg'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['24/24h', '12/12h'],
    maxDailyDose: '80 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Clopidogrel (reduz efeito)', 'Metotrexato', 'Diazepam'],
    contraindications: ['Hipersensibilidade a IBP'],
    beersListElderly: false,
  },
  {
    name: 'Pantoprazol',
    activeIngredient: 'Pantoprazol sódico',
    class: 'Inibidor de bomba de prótons (IBP)',
    commonDoses: ['20 mg', '40 mg'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['24/24h', '12/12h'],
    maxDailyDose: '80 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Metotrexato', 'Atazanavir'],
    contraindications: ['Hipersensibilidade a IBP'],
    beersListElderly: false,
  },

  // ─── Broncodilatadores ──────────────────────────────────────────
  {
    name: 'Salbutamol (Albuterol)',
    activeIngredient: 'Sulfato de salbutamol',
    class: 'Beta-2 agonista de curta duração',
    commonDoses: ['100 mcg/jato (2-4 jatos)', '2,5 mg/mL (NBZ)', '5 mg/mL (NBZ)'],
    commonRoutes: ['INH'],
    commonFrequencies: ['4/4h', '6/6h', 'SOS'],
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['Beta-bloqueadores (antagonismo)', 'Diuréticos (hipocalemia)', 'Digoxina'],
    contraindications: ['Hipersensibilidade'],
    beersListElderly: false,
  },
  {
    name: 'Brometo de Ipratrópio',
    activeIngredient: 'Brometo de ipratrópio',
    class: 'Anticolinérgico inalatório',
    commonDoses: ['250 mcg/mL (NBZ)', '20 mcg/jato (2-3 jatos)'],
    commonRoutes: ['INH'],
    commonFrequencies: ['6/6h', '8/8h'],
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['Outros anticolinérgicos (efeito aditivo)'],
    contraindications: ['Hipersensibilidade a atropina ou derivados'],
    beersListElderly: false,
  },

  // ─── Corticosteroides ───────────────────────────────────────────
  {
    name: 'Hidrocortisona',
    activeIngredient: 'Succinato sódico de hidrocortisona',
    class: 'Corticosteroide',
    commonDoses: ['100 mg', '250 mg', '500 mg'],
    commonRoutes: ['IV'],
    commonFrequencies: ['6/6h', '8/8h'],
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['AINEs (risco de sangramento GI)', 'Hipoglicemiantes', 'Anticoagulantes'],
    contraindications: ['Infecção fúngica sistêmica não tratada', 'Hipersensibilidade'],
    beersListElderly: false,
  },
  {
    name: 'Dexametasona',
    activeIngredient: 'Fosfato dissódico de dexametasona',
    class: 'Corticosteroide',
    commonDoses: ['4 mg', '8 mg', '10 mg'],
    commonRoutes: ['IV', 'VO'],
    commonFrequencies: ['6/6h', '8/8h', '12/12h', '24/24h'],
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['AINEs', 'Hipoglicemiantes', 'Anticoagulantes', 'Fenitoína'],
    contraindications: ['Infecção fúngica sistêmica', 'Vacinas com vírus vivo (relativo)'],
    beersListElderly: false,
  },
  {
    name: 'Prednisona',
    activeIngredient: 'Prednisona',
    class: 'Corticosteroide',
    commonDoses: ['5 mg', '20 mg', '40 mg', '60 mg'],
    commonRoutes: ['VO'],
    commonFrequencies: ['24/24h', '12/12h'],
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['AINEs', 'Hipoglicemiantes', 'Anticoagulantes', 'Vacinas vivas'],
    contraindications: ['Infecção fúngica sistêmica'],
    beersListElderly: false,
  },

  // ─── Psicotrópicos / Sedativos ──────────────────────────────────
  {
    name: 'Midazolam',
    activeIngredient: 'Maleato de midazolam',
    class: 'Benzodiazepínico',
    commonDoses: ['5 mg', '15 mg', '5 mg/mL IV'],
    commonRoutes: ['IV', 'IM', 'VO'],
    commonFrequencies: ['SOS', 'BIC'],
    isControlled: true,
    controlledSchedule: 'B1',
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'D',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Opioides (depressão respiratória)', 'Álcool', 'Cetoconazol', 'Eritromicina'],
    contraindications: ['Miastenia gravis', 'Insuficiência respiratória grave', 'Glaucoma de ângulo fechado', 'Gestação'],
    beersListElderly: true,
  },
  {
    name: 'Diazepam',
    activeIngredient: 'Diazepam',
    class: 'Benzodiazepínico',
    commonDoses: ['5 mg', '10 mg'],
    commonRoutes: ['VO', 'IV', 'REC'],
    commonFrequencies: ['8/8h', '12/12h', 'SOS'],
    maxDailyDose: '40 mg',
    isControlled: true,
    controlledSchedule: 'B1',
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'D',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Opioides', 'Álcool', 'Cimetidina', 'Omeprazol'],
    contraindications: ['Miastenia gravis', 'Insuficiência respiratória grave', 'Apneia do sono', 'Gestação 1º trimestre'],
    beersListElderly: true,
  },
  {
    name: 'Haloperidol',
    activeIngredient: 'Haloperidol',
    class: 'Antipsicótico típico',
    commonDoses: ['1 mg', '2,5 mg', '5 mg'],
    commonRoutes: ['VO', 'IM', 'IV'],
    commonFrequencies: ['8/8h', '12/12h', 'SOS'],
    maxDailyDose: '20 mg',
    isControlled: true,
    controlledSchedule: 'C1',
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Outros depressores do SNC', 'Lítio', 'Metoclopramida', 'QT prolongadores'],
    contraindications: ['Parkinsonismo', 'Depressão grave do SNC', 'QT prolongado'],
    beersListElderly: true,
  },

  // ─── Antieméticos ───────────────────────────────────────────────
  {
    name: 'Ondansetrona',
    activeIngredient: 'Cloridrato de ondansetrona',
    class: 'Antiemético (antagonista 5-HT3)',
    commonDoses: ['4 mg', '8 mg'],
    commonRoutes: ['IV', 'VO'],
    commonFrequencies: ['8/8h', '12/12h'],
    maxDailyDose: '32 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Tramadol (reduz efeito analgésico)', 'QT prolongadores', 'Apomorfina'],
    contraindications: ['Hipersensibilidade', 'Uso concomitante de apomorfina', 'QT longo congênito'],
    beersListElderly: false,
  },
  {
    name: 'Metoclopramida',
    activeIngredient: 'Cloridrato de metoclopramida',
    class: 'Antiemético / Procinético',
    commonDoses: ['10 mg'],
    commonRoutes: ['VO', 'IV', 'IM'],
    commonFrequencies: ['8/8h'],
    maxDailyDose: '30 mg (uso máximo 5 dias)',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['Levodopa (antagonismo)', 'Antipsicóticos (efeitos extrapiramidais aditivos)', 'Opioides'],
    contraindications: ['Feocromocitoma', 'Epilepsia', 'Obstrução GI mecânica', 'Hemorragia GI', 'Parkinson'],
    beersListElderly: true,
  },

  // ─── Cardiovasculares ───────────────────────────────────────────
  {
    name: 'AAS (Ácido Acetilsalicílico)',
    activeIngredient: 'Ácido acetilsalicílico',
    class: 'Antiplaquetário / AINE',
    commonDoses: ['100 mg', '200 mg', '300 mg'],
    commonRoutes: ['VO'],
    commonFrequencies: ['24/24h'],
    maxDailyDose: '300 mg (antiplaquetário)',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'D',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Anticoagulantes', 'AINEs', 'Metotrexato', 'Corticosteroides'],
    contraindications: ['Úlcera péptica ativa', 'Hemofilia', 'Hipersensibilidade', 'Dengue', 'Gestação 3º trimestre'],
    beersListElderly: false,
  },
  {
    name: 'Clopidogrel',
    activeIngredient: 'Bissulfato de clopidogrel',
    class: 'Antiplaquetário (Tienopiridina)',
    commonDoses: ['75 mg', '300 mg (dose de ataque)'],
    commonRoutes: ['VO'],
    commonFrequencies: ['24/24h'],
    maxDailyDose: '75 mg (manutenção)',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Omeprazol (reduz efeito)', 'AINEs', 'Anticoagulantes'],
    contraindications: ['Sangramento ativo', 'Insuficiência hepática grave'],
    beersListElderly: false,
  },
  {
    name: 'Amiodarona',
    activeIngredient: 'Cloridrato de amiodarona',
    class: 'Antiarrítmico classe III',
    commonDoses: ['100 mg', '200 mg', '150 mg IV (bolus)', '900 mg IV/24h'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['24/24h', '12/12h', 'BIC'],
    maxDailyDose: '1.200 mg (fase de ataque)',
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'D',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Warfarina', 'Digoxina', 'Fenitoína', 'Sinvastatina', 'QT prolongadores'],
    contraindications: ['Bradicardia sinusal grave', 'BAV 2º/3º grau sem MP', 'Disfunção tireoidiana grave', 'Hipersensibilidade ao iodo'],
    beersListElderly: true,
  },
  {
    name: 'Noradrenalina (Norepinefrina)',
    activeIngredient: 'Bitartarato de norepinefrina',
    class: 'Vasopressor',
    commonDoses: ['0,05-0,4 mcg/kg/min (BIC)', '4 mg/4 mL'],
    commonRoutes: ['IV'],
    commonFrequencies: ['BIC'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['IMAO', 'Antidepressivos tricíclicos', 'Beta-bloqueadores', 'Anestésicos halogenados'],
    contraindications: ['Hipovolemia não corrigida (relativa)', 'Trombose vascular (relativa)'],
    beersListElderly: false,
  },
  {
    name: 'Dobutamina',
    activeIngredient: 'Cloridrato de dobutamina',
    class: 'Inotrópico',
    commonDoses: ['2,5-20 mcg/kg/min (BIC)', '250 mg/20 mL'],
    commonRoutes: ['IV'],
    commonFrequencies: ['BIC'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['Beta-bloqueadores (antagonismo)', 'Anestésicos halogenados'],
    contraindications: ['Estenose subaórtica hipertrófica idiopática', 'Hipersensibilidade'],
    beersListElderly: false,
  },
  {
    name: 'Sinvastatina',
    activeIngredient: 'Sinvastatina',
    class: 'Estatina (inibidor da HMG-CoA redutase)',
    commonDoses: ['10 mg', '20 mg', '40 mg'],
    commonRoutes: ['VO'],
    commonFrequencies: ['24/24h (à noite)'],
    maxDailyDose: '40 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'X',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Amiodarona', 'Anlodipino (dose > 20 mg)', 'Ciclosporina', 'Gemfibrozil', 'Cetoconazol'],
    contraindications: ['Gestação', 'Doença hepática ativa', 'Elevação inexplicada de transaminases'],
    beersListElderly: false,
  },

  // ─── Sedativos / Anestésicos ────────────────────────────────────
  {
    name: 'Propofol',
    activeIngredient: 'Propofol',
    class: 'Anestésico / Sedativo IV',
    commonDoses: ['1-2 mg/kg (indução)', '1-4 mg/kg/h (manutenção BIC)'],
    commonRoutes: ['IV'],
    commonFrequencies: ['BIC'],
    isControlled: true,
    controlledSchedule: 'C1',
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['Opioides (depressão respiratória aditiva)', 'Outros sedativos'],
    contraindications: ['Hipersensibilidade a ovo/soja', 'Idade < 3 anos para sedação em UTI'],
    beersListElderly: false,
  },
  {
    name: 'Fentanil',
    activeIngredient: 'Citrato de fentanila',
    class: 'Opioide forte',
    commonDoses: ['25-100 mcg IV (bolus)', '0,5-2 mcg/kg/h (BIC)', '25 mcg/h (adesivo)'],
    commonRoutes: ['IV', 'TOP'],
    commonFrequencies: ['BIC', 'SOS'],
    isControlled: true,
    controlledSchedule: 'A1',
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Benzodiazepínicos', 'Outros opioides', 'IMAO', 'Inibidores de CYP3A4'],
    contraindications: ['Depressão respiratória', 'Uso de IMAO', 'Íleo paralítico'],
    beersListElderly: true,
  },

  // ─── Outros ─────────────────────────────────────────────────────
  {
    name: 'Cloreto de Potássio (KCl)',
    activeIngredient: 'Cloreto de potássio',
    class: 'Eletrólito',
    commonDoses: ['600 mg VO', '10 mL (KCl 19,1%) diluído em SF'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['8/8h', '12/12h'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['IECA/BRA', 'Espironolactona', 'Trimetoprima'],
    contraindications: ['Hipercalemia', 'Insuficiência renal grave com oligúria', 'Doença de Addison não tratada'],
    beersListElderly: false,
  },
  {
    name: 'Sulfato de Magnésio',
    activeIngredient: 'Sulfato de magnésio',
    class: 'Eletrólito / Tocolítico / Anticonvulsivante',
    commonDoses: ['1-2 g IV (diluído)', '4-6 g IV (eclâmpsia)'],
    commonRoutes: ['IV', 'IM'],
    commonFrequencies: ['Conforme protocolo'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'A',
    renalAdjustment: true,
    hepaticAdjustment: false,
    commonInteractions: ['Bloqueadores neuromusculares', 'Nifedipino', 'Aminoglicosídeos'],
    contraindications: ['Bloqueio cardíaco', 'Insuficiência renal grave', 'Miastenia gravis'],
    beersListElderly: false,
  },
  {
    name: 'Ranitidina',
    activeIngredient: 'Cloridrato de ranitidina',
    class: 'Antagonista H2',
    commonDoses: ['150 mg', '50 mg IV'],
    commonRoutes: ['VO', 'IV'],
    commonFrequencies: ['12/12h'],
    maxDailyDose: '300 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'B',
    renalAdjustment: true,
    hepaticAdjustment: true,
    commonInteractions: ['Cetoconazol (reduz absorção)', 'Warfarina', 'Procainamida'],
    contraindications: ['Hipersensibilidade', 'Porfiria'],
    beersListElderly: false,
  },
  {
    name: 'Prometazina',
    activeIngredient: 'Cloridrato de prometazina',
    class: 'Anti-histamínico (1ª geração)',
    commonDoses: ['25 mg', '50 mg'],
    commonRoutes: ['VO', 'IM'],
    commonFrequencies: ['8/8h', 'SOS'],
    maxDailyDose: '100 mg',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: true,
    commonInteractions: ['Depressores do SNC', 'IMAO', 'Anticolinérgicos'],
    contraindications: ['Crianças < 2 anos', 'Administração IV (risco de necrose)'],
    beersListElderly: true,
  },
  {
    name: 'Adrenalina (Epinefrina)',
    activeIngredient: 'Epinefrina',
    class: 'Catecolamina / Vasopressor',
    commonDoses: ['0,3-0,5 mg IM (anafilaxia)', '1 mg IV (PCR)', '0,01-0,3 mcg/kg/min (BIC)'],
    commonRoutes: ['IM', 'IV', 'SC'],
    commonFrequencies: ['SOS', 'BIC', '3-5 min (PCR)'],
    isControlled: false,
    isHighAlert: true,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['Beta-bloqueadores', 'Antidepressivos tricíclicos', 'IMAO', 'Anestésicos halogenados'],
    contraindications: ['Nenhuma absoluta em emergência (anafilaxia/PCR)'],
    beersListElderly: false,
  },
  {
    name: 'Atropina',
    activeIngredient: 'Sulfato de atropina',
    class: 'Anticolinérgico',
    commonDoses: ['0,5 mg IV', '1 mg IV (bradicardia/PCR)'],
    commonRoutes: ['IV'],
    commonFrequencies: ['SOS', '3-5 min (PCR)'],
    maxDailyDose: '3 mg (protocolo ACLS)',
    isControlled: false,
    isHighAlert: false,
    isAntibiotic: false,
    pregnancyCategory: 'C',
    renalAdjustment: false,
    hepaticAdjustment: false,
    commonInteractions: ['Outros anticolinérgicos', 'Amantadina', 'Anti-histamínicos'],
    contraindications: ['Glaucoma de ângulo fechado', 'Taquiarritmias', 'Miastenia gravis'],
    beersListElderly: true,
  },
] as const;

/**
 * Helper: busca medicamento por nome (busca parcial, case-insensitive).
 */
export function findMedication(query: string): readonly MedicationReference[] {
  const q = query.toLowerCase();
  return COMMON_MEDICATIONS.filter(
    (m) =>
      m.name.toLowerCase().includes(q) ||
      m.activeIngredient.toLowerCase().includes(q),
  );
}

/**
 * Helper: retorna todos os medicamentos de alta vigilância.
 */
export function getHighAlertMedications(): readonly MedicationReference[] {
  return COMMON_MEDICATIONS.filter((m) => m.isHighAlert);
}

/**
 * Helper: retorna todos os antibióticos.
 */
export function getAntibiotics(): readonly MedicationReference[] {
  return COMMON_MEDICATIONS.filter((m) => m.isAntibiotic);
}

/**
 * Helper: retorna medicamentos contraindicados em idosos (Beers List).
 */
export function getBeersListMedications(): readonly MedicationReference[] {
  return COMMON_MEDICATIONS.filter((m) => m.beersListElderly);
}
