export interface NICIntervention {
  code: string;
  title: string;
  titleEn: string;
  definition: string;
  activities: string[];
  relatedNANDA: string[];
}

/**
 * Intervenções de Enfermagem NIC mais utilizadas em hospitais brasileiros.
 */
export const NIC_INTERVENTIONS: readonly NICIntervention[] = [
  {
    code: '1400',
    title: 'Controle da dor',
    titleEn: 'Pain Management',
    definition: 'Alívio ou redução da dor a um nível de conforto aceitável pelo paciente',
    activities: [
      'Realizar avaliação abrangente da dor (localização, características, duração, frequência, qualidade, intensidade)',
      'Observar indicadores não verbais de desconforto',
      'Assegurar analgesia pré-procedimento',
      'Utilizar estratégias de comunicação terapêutica para reconhecer a experiência da dor',
      'Investigar fatores que aliviam/pioram a dor',
      'Avaliar eficácia das medidas de controle da dor',
      'Administrar analgésicos conforme prescrição médica',
      'Promover repouso/sono adequado para facilitar alívio da dor',
      'Aplicar medidas não farmacológicas (compressas, mudança de posição, massagem)',
      'Registrar resposta ao tratamento analgésico',
    ],
    relatedNANDA: ['00132', '00133'],
  },
  {
    code: '6540',
    title: 'Controle de infecção',
    titleEn: 'Infection Control',
    definition: 'Minimizar a aquisição e transmissão de agentes infecciosos',
    activities: [
      'Higienizar as mãos antes e após contato com o paciente',
      'Usar EPI conforme protocolo institucional',
      'Monitorar sinais e sintomas de infecção sistêmica e localizada',
      'Manter técnica asséptica em procedimentos invasivos',
      'Trocar curativos de acesso venoso conforme protocolo',
      'Monitorar hemograma (leucócitos)',
      'Administrar antibióticos conforme prescrição',
      'Orientar paciente e família sobre prevenção de infecção',
      'Isolar paciente conforme tipo de precaução indicada',
      'Garantir descarte adequado de materiais perfurocortantes',
    ],
    relatedNANDA: ['00004'],
  },
  {
    code: '6490',
    title: 'Prevenção de quedas',
    titleEn: 'Fall Prevention',
    definition: 'Instituir precauções especiais em paciente com risco de lesão por queda',
    activities: [
      'Identificar fatores de risco para quedas (Escala de Morse)',
      'Sinalizar paciente com risco de queda (pulseira, placa no leito)',
      'Manter grades do leito elevadas',
      'Orientar paciente e família sobre riscos e prevenção',
      'Manter campainha ao alcance do paciente',
      'Auxiliar na deambulação',
      'Manter ambiente livre de obstáculos',
      'Iluminação adequada no quarto e banheiro',
      'Revisar medicamentos que aumentam risco (sedativos, anti-hipertensivos)',
      'Encaminhar para fisioterapia quando indicado',
    ],
    relatedNANDA: ['00155'],
  },
  {
    code: '3540',
    title: 'Prevenção de lesão por pressão',
    titleEn: 'Pressure Ulcer Prevention',
    definition: 'Prevenção de lesões por pressão em paciente com risco',
    activities: [
      'Avaliar risco utilizando Escala de Braden na admissão e periodicamente',
      'Realizar mudança de decúbito a cada 2 horas',
      'Manter lençóis esticados e sem pregas',
      'Utilizar colchão adequado (pneumático, piramidal)',
      'Hidratar a pele com creme hidratante',
      'Manter pele limpa e seca',
      'Proteger proeminências ósseas com coxins',
      'Monitorar estado nutricional',
      'Inspecionar a pele em cada troca de posição',
      'Documentar condição da pele a cada turno',
    ],
    relatedNANDA: ['00046', '00047', '00205'],
  },
  {
    code: '4120',
    title: 'Controle hídrico',
    titleEn: 'Fluid Management',
    definition: 'Promoção do equilíbrio hídrico e prevenção de complicações resultantes de níveis anormais de líquidos',
    activities: [
      'Monitorar balanço hídrico (ingestão e eliminação)',
      'Pesar paciente diariamente',
      'Monitorar sinais vitais',
      'Avaliar sinais de desidratação ou sobrecarga hídrica',
      'Manter acesso venoso pérvio',
      'Administrar fluidos IV conforme prescrição',
      'Monitorar eletrólitos séricos',
      'Orientar sobre restrição ou estímulo hídrico',
      'Avaliar turgor da pele e mucosas',
      'Registrar débito urinário',
    ],
    relatedNANDA: ['00025', '00026', '00027'],
  },
  {
    code: '1100',
    title: 'Controle da nutrição',
    titleEn: 'Nutrition Management',
    definition: 'Auxílio ou provisão de ingestão dietética balanceada de alimentos e líquidos',
    activities: [
      'Determinar as preferências alimentares do paciente',
      'Avaliar estado nutricional (peso, IMC, albumina)',
      'Monitorar ingestão calórica e de nutrientes',
      'Oferecer alimentos em porções pequenas e frequentes',
      'Orientar sobre dieta prescrita',
      'Solicitar avaliação da nutricionista',
      'Monitorar resultados laboratoriais (albumina, pré-albumina, proteínas totais)',
      'Promover ambiente agradável durante refeições',
      'Auxiliar na alimentação quando necessário',
      'Registrar aceitação da dieta',
    ],
    relatedNANDA: ['00002'],
  },
  {
    code: '3320',
    title: 'Oxigenoterapia',
    titleEn: 'Oxygen Therapy',
    definition: 'Administração de oxigênio e monitorização de sua eficácia',
    activities: [
      'Manter vias aéreas desobstruídas',
      'Administrar oxigênio suplementar conforme prescrição',
      'Monitorar fluxo de oxigênio',
      'Monitorar SpO2 continuamente ou conforme protocolo',
      'Avaliar padrão respiratório (frequência, profundidade, esforço)',
      'Posicionar paciente para maximizar ventilação (cabeceira elevada)',
      'Verificar gasometria arterial quando indicado',
      'Observar sinais de toxicidade por oxigênio',
      'Manter umidificação adequada do sistema',
      'Orientar paciente sobre uso correto do dispositivo',
    ],
    relatedNANDA: ['00030', '00032'],
  },
  {
    code: '3160',
    title: 'Aspiração de vias aéreas',
    titleEn: 'Airway Suctioning',
    definition: 'Remoção de secreções de vias aéreas por inserção de cateter de aspiração',
    activities: [
      'Auscultar sons pulmonares antes e após aspiração',
      'Informar ao paciente sobre o procedimento',
      'Selecionar calibre adequado do cateter de aspiração',
      'Utilizar técnica asséptica',
      'Hiperventilar com oxigênio a 100% antes da aspiração',
      'Limitar tempo de aspiração a 10-15 segundos',
      'Monitorar SpO2 e frequência cardíaca durante o procedimento',
      'Registrar características da secreção (volume, cor, consistência)',
      'Monitorar estado respiratório após o procedimento',
      'Manter material de emergência disponível',
    ],
    relatedNANDA: ['00031'],
  },
  {
    code: '4040',
    title: 'Cuidados cardíacos',
    titleEn: 'Cardiac Care',
    definition: 'Limitação de complicações resultantes de desequilíbrio entre oferta e demanda de oxigênio miocárdico',
    activities: [
      'Monitorar ritmo e frequência cardíaca',
      'Avaliar dor torácica (intensidade, localização, irradiação, duração)',
      'Realizar ECG de 12 derivações conforme necessário',
      'Monitorar sinais vitais frequentemente',
      'Monitorar balanço hídrico e débito urinário',
      'Promover repouso no leito na fase aguda',
      'Administrar medicamentos cardiológicos conforme prescrição',
      'Monitorar efeitos colaterais dos medicamentos',
      'Avaliar tolerância à atividade progressivamente',
      'Orientar sobre sinais de alerta',
    ],
    relatedNANDA: ['00029'],
  },
  {
    code: '4066',
    title: 'Cuidados circulatórios: insuficiência arterial',
    titleEn: 'Circulatory Care: Arterial Insufficiency',
    definition: 'Promoção da circulação arterial',
    activities: [
      'Avaliar circulação periférica (pulsos, cor, temperatura, enchimento capilar)',
      'Manter extremidades aquecidas',
      'Evitar compressão de membros',
      'Monitorar grau de desconforto ou dor',
      'Posicionar membros em posição declive',
      'Incentivar exercícios de amplitude de movimento',
      'Administrar antiagregantes ou anticoagulantes conforme prescrição',
      'Orientar sobre cuidados com os pés',
      'Orientar sobre cessação do tabagismo',
      'Monitorar sinais de trombose',
    ],
    relatedNANDA: ['00024'],
  },
  {
    code: '5820',
    title: 'Redução da ansiedade',
    titleEn: 'Anxiety Reduction',
    definition: 'Minimizar apreensão, receio, pressentimento ou desconforto relacionados a uma fonte não identificada de perigo antecipado',
    activities: [
      'Utilizar abordagem calma e tranquilizadora',
      'Explicar todos os procedimentos, incluindo sensações prováveis',
      'Permanecer com o paciente para promover segurança',
      'Encorajar verbalização de sentimentos e percepções',
      'Identificar mudanças no nível de ansiedade',
      'Orientar sobre técnicas de relaxamento',
      'Administrar ansiolíticos conforme prescrição',
      'Oferecer informações sobre diagnóstico, tratamento e prognóstico',
      'Facilitar presença de familiar/acompanhante',
      'Manter ambiente calmo e silencioso',
    ],
    relatedNANDA: ['00146', '00148'],
  },
  {
    code: '2300',
    title: 'Administração de medicamentos',
    titleEn: 'Medication Administration',
    definition: 'Preparação, administração e avaliação da eficácia de medicamentos prescritos',
    activities: [
      'Seguir os nove certos da administração de medicamentos',
      'Verificar prescrição médica antes da administração',
      'Verificar alergias do paciente',
      'Conferir nome, dose, via, horário e validade',
      'Orientar paciente sobre o medicamento administrado',
      'Registrar administração no prontuário',
      'Monitorar efeitos terapêuticos e adversos',
      'Realizar dupla checagem para medicamentos de alta vigilância',
      'Notificar eventos adversos ou erros de medicação',
      'Avaliar compatibilidade de medicamentos em mesma via',
    ],
    relatedNANDA: ['00132', '00004', '00078'],
  },
  {
    code: '1800',
    title: 'Assistência no autocuidado',
    titleEn: 'Self-Care Assistance',
    definition: 'Assistir o paciente a realizar atividades de vida diária',
    activities: [
      'Avaliar capacidade do paciente para autocuidado',
      'Encorajar independência, mas intervir quando necessário',
      'Fornecer itens pessoais ao alcance',
      'Auxiliar no banho, higiene oral, vestimenta e alimentação',
      'Promover dignidade e privacidade',
      'Estabelecer rotina de atividades de autocuidado',
      'Monitorar capacidade funcional progressivamente',
      'Ensinar técnicas adaptativas quando necessário',
      'Envolver família no plano de cuidados',
      'Registrar nível de dependência',
    ],
    relatedNANDA: ['00108', '00102'],
  },
  {
    code: '6680',
    title: 'Monitoração de sinais vitais',
    titleEn: 'Vital Signs Monitoring',
    definition: 'Coleta e análise de dados cardiovasculares, respiratórios e de temperatura corporal para determinar e prevenir complicações',
    activities: [
      'Monitorar PA, pulso, temperatura, FR e SpO2',
      'Monitorar e registrar sinais de hipo/hipertermia',
      'Identificar possíveis causas de alterações nos sinais vitais',
      'Verificar adequação de manguito de PA',
      'Monitorar presença de pulso paradoxal',
      'Monitorar padrão respiratório',
      'Monitorar oximetria de pulso',
      'Comunicar alterações significativas ao médico',
      'Registrar tendências e variações',
      'Ajustar frequência de monitorização conforme condição clínica',
    ],
    relatedNANDA: ['00029', '00030', '00032', '00007', '00006'],
  },
  {
    code: '5602',
    title: 'Ensino: processo de doença',
    titleEn: 'Teaching: Disease Process',
    definition: 'Assistir o paciente a compreender informações relacionadas a um processo de doença específico',
    activities: [
      'Avaliar nível atual de conhecimento do paciente sobre a doença',
      'Explicar fisiopatologia da doença em linguagem acessível',
      'Descrever sinais e sintomas comuns',
      'Orientar sobre opções de tratamento',
      'Discutir mudanças no estilo de vida necessárias',
      'Orientar sobre medicamentos (ação, dose, efeitos colaterais)',
      'Orientar sobre quando procurar atendimento de emergência',
      'Fornecer material educativo quando disponível',
      'Reforçar informações em cada interação',
      'Avaliar compreensão do paciente',
    ],
    relatedNANDA: ['00126', '00078'],
  },
  {
    code: '3900',
    title: 'Regulação da temperatura',
    titleEn: 'Temperature Regulation',
    definition: 'Alcance e/ou manutenção da temperatura corporal dentro de variação normal',
    activities: [
      'Monitorar temperatura a cada 1-4 horas conforme indicação',
      'Administrar antitérmicos conforme prescrição',
      'Aplicar compressas mornas para febre',
      'Aplicar cobertores para hipotermia',
      'Monitorar e registrar sinais de hipo/hipertermia',
      'Ajustar temperatura ambiente',
      'Remover excesso de roupas de cama em febre',
      'Estimular ingesta hídrica',
      'Monitorar sinais de convulsão febril em crianças',
      'Coletar hemoculturas antes de iniciar antibióticos em febre',
    ],
    relatedNANDA: ['00007', '00006'],
  },
  {
    code: '0840',
    title: 'Posicionamento',
    titleEn: 'Positioning',
    definition: 'Movimentar deliberadamente o paciente ou parte do corpo para promover bem-estar fisiológico e/ou psicológico',
    activities: [
      'Posicionar paciente em alinhamento corporal adequado',
      'Elevar cabeceira do leito conforme indicação',
      'Imobilizar ou apoiar parte do corpo afetada',
      'Elevar membro afetado',
      'Evitar posicionar sobre local de lesão/cirurgia',
      'Utilizar coxins e travesseiros para apoio',
      'Incentivar exercícios ativos de amplitude de movimento',
      'Realizar mudança de decúbito conforme protocolo',
      'Documentar posição e horário de cada mudança',
      'Monitorar integridade da pele em pontos de pressão',
    ],
    relatedNANDA: ['00085', '00205'],
  },
  {
    code: '0580',
    title: 'Cateterismo vesical',
    titleEn: 'Urinary Catheterization',
    definition: 'Inserção de cateter na bexiga para drenagem temporária ou permanente de urina',
    activities: [
      'Avaliar necessidade do cateterismo',
      'Explicar procedimento ao paciente',
      'Usar técnica asséptica rigorosa',
      'Selecionar calibre adequado do cateter',
      'Fixar cateter adequadamente',
      'Manter sistema de drenagem fechado',
      'Monitorar débito urinário (volume, cor, aspecto)',
      'Realizar higiene perineal a cada turno',
      'Avaliar diariamente necessidade de manutenção do cateter',
      'Registrar volume e características da urina',
    ],
    relatedNANDA: ['00016'],
  },
  {
    code: '0450',
    title: 'Controle da constipação/impactação',
    titleEn: 'Constipation/Impaction Management',
    definition: 'Prevenção e alívio da constipação/impactação',
    activities: [
      'Monitorar ruídos hidroaéreos',
      'Avaliar padrão de eliminação intestinal',
      'Estimular aumento da ingestão de líquidos',
      'Orientar sobre dieta rica em fibras',
      'Encorajar aumento da atividade física quando possível',
      'Administrar laxantes ou enemas conforme prescrição',
      'Monitorar sinais de impactação fecal',
      'Orientar sobre posição adequada para evacuação',
      'Registrar frequência, consistência e volume das evacuações',
      'Consultar equipe médica se constipação persistir',
    ],
    relatedNANDA: ['00011'],
  },
  {
    code: '6200',
    title: 'Cuidados em emergência',
    titleEn: 'Emergency Care',
    definition: 'Prover cuidados salvadores de vida em situações de risco de morte',
    activities: [
      'Avaliar e manter via aérea, respiração e circulação (ABC)',
      'Monitorar sinais vitais continuamente',
      'Obter acesso venoso calibroso',
      'Administrar medicamentos de emergência conforme protocolo',
      'Preparar e auxiliar em intubação orotraqueal se necessário',
      'Iniciar RCP se indicado',
      'Monitorar ritmo cardíaco',
      'Coletar exames laboratoriais de urgência',
      'Manter equipamento de emergência funcionante e disponível',
      'Documentar todos os procedimentos e horários',
    ],
    relatedNANDA: ['00029', '00030', '00031', '00032'],
  },
] as const;

/**
 * Helper: busca intervenções NIC por código NANDA relacionado.
 */
export function getNICByNANDA(nandaCode: string): readonly NICIntervention[] {
  return NIC_INTERVENTIONS.filter((i) => i.relatedNANDA.includes(nandaCode));
}
