import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsUUID,
  IsOptional,
  IsEnum,
  IsBoolean,
  IsDateString,
  IsArray,
  ValidateNested,
  ArrayMinSize,
} from 'class-validator';
import { Type } from 'class-transformer';
import { PrescriptionType } from '@prisma/client';
import { CreatePrescriptionItemDto } from './create-prescription-item.dto';

export class CreatePrescriptionDto {
  @ApiProperty({ description: 'Encounter ID' })
  @IsUUID()
  @IsNotEmpty()
  encounterId: string;

  @ApiProperty({ description: 'Patient ID' })
  @IsUUID()
  @IsNotEmpty()
  patientId: string;

  @ApiProperty({ description: 'Prescription type', enum: PrescriptionType })
  @IsEnum(PrescriptionType)
  type: PrescriptionType;

  @ApiPropertyOptional({ description: 'Voice transcription ID' })
  @IsOptional()
  @IsUUID()
  voiceTranscriptionId?: string;

  @ApiPropertyOptional({ description: 'Was generated by AI' })
  @IsOptional()
  @IsBoolean()
  wasGeneratedByAI?: boolean;

  @ApiPropertyOptional({ description: 'Valid from date' })
  @IsOptional()
  @IsDateString()
  validFrom?: string;

  @ApiPropertyOptional({ description: 'Valid until date' })
  @IsOptional()
  @IsDateString()
  validUntil?: string;

  @ApiPropertyOptional({ description: 'Is one-time prescription' })
  @IsOptional()
  @IsBoolean()
  isOneTime?: boolean;

  @ApiPropertyOptional({ description: 'Is continuous prescription' })
  @IsOptional()
  @IsBoolean()
  isContinuous?: boolean;

  @ApiPropertyOptional({ description: 'Is PRN (as needed)' })
  @IsOptional()
  @IsBoolean()
  isPRN?: boolean;

  @ApiPropertyOptional({ description: 'Requires double check' })
  @IsOptional()
  @IsBoolean()
  requiresDoubleCheck?: boolean;

  @ApiProperty({ description: 'Prescription items', type: [CreatePrescriptionItemDto] })
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => CreatePrescriptionItemDto)
  items: CreatePrescriptionItemDto[];
}
